### PR TITLE
Update Get-VisualStudio.ps1

### PR DESCRIPTION
**Pull request by jkucinski**
I added parameter "-Product *" to command Get-VSSetupInstance.
This fix allows use this script with Visual Studio Build Tools 2019.

### CODE REVIEW

**Comment by ericwj** [comment]
Thanks @jkucinski,

But even after I install *Visual Studio Build Tools 2019*, I don't see any difference after including this switch. I still get *Visual Studio Community 2019* as the result.

EDIT: I do get Build Tools without the `-Prerelease` switch but I don't think it is proper to depend on the date or version (whichever the `-Latest` switch selects on) to distinguish between build tools and *Visual Studio* itself.

I think the proper thing to do is to add a parameter or pass-through a parameter to `Select-VSSetupInstance` from remaining arguments.

**Comment by ericwj** [comment]
```PS
PS VisualStudioShell> Get-VSSetupInstance -Prerelease

InstanceId          : 98b612fa
DisplayName         : Visual Studio Build Tools 2019
InstallationVersion : 16.7.30503.244
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
InstallDate         : 17/09/2020 14:51:33

InstanceId          : b2d240dc
DisplayName         : Visual Studio Community 2019
InstallationVersion : 16.7.30330.147
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
InstallDate         : 02/04/2019 21:32:10

InstanceId          : f80816f7
DisplayName         : Visual Studio Community 2019
InstallationVersion : 16.8.30404.54
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
InstallDate         : 06/12/2018 00:23:16


PS VisualStudioShell> Get-VSSetupInstance -Prerelease | Select-VSSetupInstance -Latest

InstanceId          : f80816f7
DisplayName         : Visual Studio Community 2019
InstallationVersion : 16.8.30404.54
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
InstallDate         : 06/12/2018 00:23:16


PS VisualStudioShell> Get-VSSetupInstance -Prerelease | Select-VSSetupInstance -Latest -Product *

InstanceId          : f80816f7
DisplayName         : Visual Studio Community 2019
InstallationVersion : 16.8.30404.54
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
InstallDate         : 06/12/2018 00:23:16
```

**Comment by ghost** [comment]
The problem occurs when installed only Visual Studio Build Tools 2019.

```
PS D:\> Get-VSSetupInstance -Prerelease | Select-VSSetupInstance -Latest

PS D:\> Get-VSSetupInstance -Prerelease | Select-VSSetupInstance -Latest -Product *

InstanceId          : acbd0952
DisplayName         : Visual Studio Build Tools 2019
InstallationVersion : 16.7.30503.244
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
InstallDate         : 08.09.2020 15:35:53
```

More explain find on this [link](https://github.com/microsoft/vssetup.powershell/issues/56#issuecomment-540789660l).

**Comment by ericwj** [comment]
Yeah I updated the comment above, but obviously you beat me, responding faster than I could type ;)

**Comment by ghost** [comment]
Take it easy :)
I wanna just help to update very useful script.

**Comment by ericwj** [comment]
Yes, thanks for that.

Can you add an optional `$Product` parameter to `Get-VisualStudio` - which needs to be splatted because `$null` or `""` will produce errors. Then you should not provide `*` as value but something like this since `*` is brittle and will break whenever the ordering of versions changes between *Visual Studio* and the build tools.

```PS
Get-VSSetupInstance | Select-VSSetupInstance -Product "*Build*"
```

**Comment by ericwj** [comment]
It'd also be fine if you choose to add a switch to `Get-VisualStudio`, say `-BuildTools` and hardcode `Microsoft.VisualStudio.Product.BuildTools*` as the `$Product` argument to `Select-VSSetupInstance` if that switch is present.

That is probably more usable.

**Comment by ghost** [comment]
Ok, I created new [pull request](https://github.com/ericwj/VisualStudioShell/pull/2) for this fix.

**Pull request closed without merging**
