### PR TITLE
Jkucinski vs product patch

### PR DESCRIPTION
**Pull request by jkucinski**
I created fix to use mainly with Visual Studio Build Tools, but we can now choice installed version of Visual Studio.

### CODE REVIEW

**Comment by ericwj** [comment]
I'm new to this - to be on the receiving end at least. Shouldn't you push to a branch in this repository and not to `master`?

I would also like to receive a squashed commit.

Dereferencing `$Product.Length` isn't proper even if PowerShell accepts it. It is better to do a `$null` check on `$Product` itself. I don't quite care to special-case the empty string anyway. If it is specified explicitly, use it as-is. So don't check `Length` at all.

And can you rename `VsProduct` to just `Product`? I don't have any kind of prefixes anywhere and I dislike them.

**Comment by ghost** [comment]
I changed test argument '$VSProduct' and '$Product' from check 'Length' property to check 'IsNullOrEmpty' from String class.

You should select 'Squash and merge' for this pull request.

**Review by ericwj — CHANGES_REQUESTED** [review]
The expression assigned to `$VS` should be indented relative to the `$VS =` line.

**Review by ericwj — CHANGES_REQUESTED** [review]
Can you change the help for the `Product` argument to be the same as the help for `Select-VSSetupInstance`?

**Review by ericwj — CHANGES_REQUESTED** [review]
The `Product` argument for `Select-VSSetupInstance` is actually `[string[]]` not `[string]`. Please have them match types.

**Comment by ericwj** [comment]
Also the whitespace isn't correct. You should honor `.editorconfig` settings. The indent style is tab.

I'm sorry for the many remarks, but I (mis)use this to learn how this works ;)

**Comment by ghost** [comment]
Easy :)
I made few changes:
- change type of parameter `$Product` from `string` to `string[]`
- change test parameter `$Product` to check `$null`
- change description parameter `$Product` to be same as in `Get/Set-VSSetupInstance`
- change indent style from `spaces` to `tab`

I'm only begining learn write PowerShell's scripts :)

**Comment by ghost** [comment]
Code after made all my changes is clean.
If you thing that changes are ok, you can merge this pull to master branch.

**Review by ericwj — CHANGES_REQUESTED** [review]
`Format-VisualStudioShellArguments.ps1` still has one single line with space indentations.

**Comment by ghost** [comment]
Now, it should be ok.

**Review by ericwj — APPROVED** [review]

**Comment by ericwj** [comment]
Oh why did you add `.Parameter Product` to `Format-VisualStudioShellArguments`? The product argument is not an argument to `VsDevCmd.bat`, but will select `VsDevCmd.bat` from `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools` instead of a Visual Studio version.

**Review by ericwj — CHANGES_REQUESTED** [review]
Remove the `.Parameter Product` section.

**Comment by ghost** [comment]
I removed `Product` parameter from `Format-VisualStudioShellArguments.ps1`. I added by mistake. Now, it's fixed.

**Comment by ericwj** [comment]
Thanks! You get a 10 for making the improvement, I get a lousy 6 for reviewer efficiency. Alltogether, it's 8! *GOOD*! ;)

**Comment by ericwj** [comment]
These changes and a few others were released as part of version 0.4.0, which is now on the PowerShell Gallery.

**Pull request merged**
